[phases.setup]
nixPkgs = ["python3", "python312Packages.pip", "poppler_utils", "gcc", "zlib", "libjpeg"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn server:app --bind 0.0.0.0:$PORT"

